import 'package:marketna_app/constants/text/dio_exception_text.dart';

class DioExceptionTranslations {
  Map<String, String> get keys => {
        DioExceptionText.badResponse:
            'عفوًا! يبدو أننا واجهنا استجابة سيئة من السيرفر.',
        DioExceptionText.connectionError:
            "عفوا! يبدو أننا نواجه مشكلة في الاتصال بالخادم. يرجى التحقق من اتصالك بالإنترنت والمحاولة مرة أخرى.",
        DioExceptionText.connectionTimeout:
            "أوه! يبدو أن مهلة الاتصال بالخادم قد انتهت. يرجى التحقق من اتصالك بالإنترنت والمحاولة مرة أخرى لاحقًا. نعتذر عن الإزعاج.",
        DioExceptionText.defaultError: "عفوا! شيء ما حدث بشكل خاطئ",
        DioExceptionText.receiveTimeout:
            "أوه لا! يبدو أن وصول البيانات التي كنا نتوقعها استغرق وقتًا أطول من المتوقع. يرجى التحقق من اتصالك بالإنترنت والمحاولة مرة أخرى. إذا استمرت المشكلة، يرجى الاتصال بفريق الدعم لدينا للحصول على مزيد من المساعدة. نعتذر عن أي إزعاج قد يسببه ذلك.",
        DioExceptionText.requestCancel:
            "عفوا! يبدو أن طلبك قد تم إلغاؤه. يرجى التأكد من تقديم جميع المعلومات المطلوبة والمحاولة مرة أخرى. إذا كنت لا تزال تواجه مشكلات، فيرجى التواصل مع فريق الدعم لدينا للحصول على مزيد من المساعدة. ونحن نعتذر عن أي إزعاج قد تسببنا فيه. ",
        DioExceptionText.sendTimeout:
            "آه! يبدو أنه حدث تأخير في إرسال طلبك. يرجى التحقق من اتصالك بالإنترنت والمحاولة مرة أخرى. إذا استمرت المشكلة، يرجى الاتصال بفريق الدعم لدينا للحصول على مزيد من المساعدة. ونحن نعتذر عن أي إزعاج قد يسببه ذلك.",
        DioExceptionText.unknownError: 'عفوا! شيء ما حدث بشكل خاطئ',
      };
}

